# Generated by Django 2.1 on 2018-08-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'todo',
                'db_table': 'todos',
                'verbose_name_plural': 'todos',
            },
        ),
    ]
